name = "uss"

[namespace.storage.new]
required = ["name", "credential"]
optional = ["storage_features", "default_storage_pairs", "work_dir", "http_client_options"]

[namespace.storage.op.list]
optional = ["list_mode", "continuation_token"]

[namespace.storage.op.read]
optional = ["io_callback"]
virtual = ["offset", "size"]

[namespace.storage.op.write]
optional = ["io_callback"]
virtual = ["content_md5", "content_type"]

[pairs.storage_features]
type = "StorageFeatures"
description = "set storage features"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"
